// Generated by scripts/optimize-images.mjs. Originals are preserved.
export default {
  "/hero-bg.jpeg": {
    "width": 1536,
    "height": 1024,
    "src": "/optimized/hero-bg-1440.webp",
    "srcSet": "/optimized/hero-bg-640.webp 640w, /optimized/hero-bg-1440.webp 1440w"
  },
  "/home-nursing.png": {
    "width": 1537,
    "height": 1023,
    "src": "/optimized/home-nursing-1440.webp",
    "srcSet": "/optimized/home-nursing-640.webp 640w, /optimized/home-nursing-1440.webp 1440w"
  },
  "/home-post-surgical.png": {
    "width": 1536,
    "height": 1024,
    "src": "/optimized/home-post-surgical-1440.webp",
    "srcSet": "/optimized/home-post-surgical-640.webp 640w, /optimized/home-post-surgical-1440.webp 1440w"
  },
  "/home-chronic.png": {
    "width": 1536,
    "height": 1024,
    "src": "/optimized/home-chronic-1440.webp",
    "srcSet": "/optimized/home-chronic-640.webp 640w, /optimized/home-chronic-1440.webp 1440w"
  },
  "/home-companion.png": {
    "width": 1672,
    "height": 941,
    "src": "/optimized/home-companion-1440.webp",
    "srcSet": "/optimized/home-companion-640.webp 640w, /optimized/home-companion-1440.webp 1440w"
  },
  "/home-personal.png": {
    "width": 1537,
    "height": 1023,
    "src": "/optimized/home-personal-1440.webp",
    "srcSet": "/optimized/home-personal-640.webp 640w, /optimized/home-personal-1440.webp 1440w"
  },
  "/home-medication.png": {
    "width": 1456,
    "height": 816,
    "src": "/optimized/home-medication-1440.webp",
    "srcSet": "/optimized/home-medication-640.webp 640w, /optimized/home-medication-1440.webp 1440w"
  },
  "/care-scenes/garden-companionship.png": {
    "width": 1536,
    "height": 1024,
    "src": "/optimized/care-scenes-garden-companionship-1440.webp",
    "srcSet": "/optimized/care-scenes-garden-companionship-640.webp 640w, /optimized/care-scenes-garden-companionship-1440.webp 1440w"
  },
  "/advanced_care.jpeg": {
    "width": 1600,
    "height": 872,
    "src": "/optimized/advanced-care-1440.webp",
    "srcSet": "/optimized/advanced-care-640.webp 640w, /optimized/advanced-care-1440.webp 1440w"
  },
  "/care-scenes/nighttime-nursing.png": {
    "width": 1536,
    "height": 1024,
    "src": "/optimized/care-scenes-nighttime-nursing-1440.webp",
    "srcSet": "/optimized/care-scenes-nighttime-nursing-640.webp 640w, /optimized/care-scenes-nighttime-nursing-1440.webp 1440w"
  },
  "/care-scenes/memory-support.png": {
    "width": 1536,
    "height": 1024,
    "src": "/optimized/care-scenes-memory-support-1440.webp",
    "srcSet": "/optimized/care-scenes-memory-support-640.webp 640w, /optimized/care-scenes-memory-support-1440.webp 1440w"
  },
  "/care-scenes/groceries-doorstep.png": {
    "width": 1536,
    "height": 1024,
    "src": "/optimized/care-scenes-groceries-doorstep-1440.webp",
    "srcSet": "/optimized/care-scenes-groceries-doorstep-640.webp 640w, /optimized/care-scenes-groceries-doorstep-1440.webp 1440w"
  },
  "/care-scenes/evening-handoff.png": {
    "width": 1536,
    "height": 1024,
    "src": "/optimized/care-scenes-evening-handoff-1440.webp",
    "srcSet": "/optimized/care-scenes-evening-handoff-640.webp 640w, /optimized/care-scenes-evening-handoff-1440.webp 1440w"
  },
  "/care-scenes/specialized-support.png": {
    "width": 1536,
    "height": 1024,
    "src": "/optimized/care-scenes-specialized-support-1440.webp",
    "srcSet": "/optimized/care-scenes-specialized-support-640.webp 640w, /optimized/care-scenes-specialized-support-1440.webp 1440w"
  },
  "/IMG_2598.JPG": {
    "width": 380,
    "height": 380,
    "src": "/optimized/img-2598-380.webp",
    "srcSet": "/optimized/img-2598-380.webp 380w"
  },
  "/care-scenes/personal-hygiene.png": {
    "width": 1536,
    "height": 1024,
    "src": "/optimized/care-scenes-personal-hygiene-1440.webp",
    "srcSet": "/optimized/care-scenes-personal-hygiene-640.webp 640w, /optimized/care-scenes-personal-hygiene-1440.webp 1440w"
  },
  "/care-scenes/walker-support.png": {
    "width": 1536,
    "height": 1024,
    "src": "/optimized/care-scenes-walker-support-1440.webp",
    "srcSet": "/optimized/care-scenes-walker-support-640.webp 640w, /optimized/care-scenes-walker-support-1440.webp 1440w"
  },
  "/meal_preparation.png": {
    "width": 1408,
    "height": 768,
    "src": "/optimized/meal-preparation-1408.webp",
    "srcSet": "/optimized/meal-preparation-640.webp 640w, /optimized/meal-preparation-1408.webp 1408w"
  },
  "/care-scenes/post-surgery-visit.png": {
    "width": 1697,
    "height": 927,
    "src": "/optimized/care-scenes-post-surgery-visit-1440.webp",
    "srcSet": "/optimized/care-scenes-post-surgery-visit-640.webp 640w, /optimized/care-scenes-post-surgery-visit-1440.webp 1440w"
  },
  "/care-scenes/stroke-recovery.png": {
    "width": 1536,
    "height": 1024,
    "src": "/optimized/care-scenes-stroke-recovery-1440.webp",
    "srcSet": "/optimized/care-scenes-stroke-recovery-640.webp 640w, /optimized/care-scenes-stroke-recovery-1440.webp 1440w"
  },
  "/care-scenes/incision-dressing.png": {
    "width": 1536,
    "height": 1024,
    "src": "/optimized/care-scenes-incision-dressing-1440.webp",
    "srcSet": "/optimized/care-scenes-incision-dressing-640.webp 640w, /optimized/care-scenes-incision-dressing-1440.webp 1440w"
  },
  "/medication_ad.png": {
    "width": 1408,
    "height": 768,
    "src": "/optimized/medication-ad-1408.webp",
    "srcSet": "/optimized/medication-ad-640.webp 640w, /optimized/medication-ad-1408.webp 1408w"
  },
  "/Layer 8.png": {
    "width": 1077,
    "height": 719,
    "src": "/optimized/layer-8-1077.webp",
    "srcSet": "/optimized/layer-8-640.webp 640w, /optimized/layer-8-1077.webp 1077w"
  },
  "/care-scenes/temporary-relief.png": {
    "width": 1536,
    "height": 1024,
    "src": "/optimized/care-scenes-temporary-relief-1440.webp",
    "srcSet": "/optimized/care-scenes-temporary-relief-640.webp 640w, /optimized/care-scenes-temporary-relief-1440.webp 1440w"
  },
  "/care-scenes/planned-respite.png": {
    "width": 1697,
    "height": 927,
    "src": "/optimized/care-scenes-planned-respite-1440.webp",
    "srcSet": "/optimized/care-scenes-planned-respite-640.webp 640w, /optimized/care-scenes-planned-respite-1440.webp 1440w"
  },
  "/care-scenes/urgent-respite-call.png": {
    "width": 1536,
    "height": 1024,
    "src": "/optimized/care-scenes-urgent-respite-call-1440.webp",
    "srcSet": "/optimized/care-scenes-urgent-respite-call-640.webp 640w, /optimized/care-scenes-urgent-respite-call-1440.webp 1440w"
  },
  "/care-scenes/respite-family-departure.png": {
    "width": 1536,
    "height": 1024,
    "src": "/optimized/care-scenes-respite-family-departure-1440.webp",
    "srcSet": "/optimized/care-scenes-respite-family-departure-640.webp 640w, /optimized/care-scenes-respite-family-departure-1440.webp 1440w"
  },
  "/Layer 9.png": {
    "width": 1032,
    "height": 799,
    "src": "/optimized/layer-9-1032.webp",
    "srcSet": "/optimized/layer-9-640.webp 640w, /optimized/layer-9-1032.webp 1032w"
  },
  "/care-scenes/recovery-assistance.png": {
    "width": 1536,
    "height": 1024,
    "src": "/optimized/care-scenes-recovery-assistance-1440.webp",
    "srcSet": "/optimized/care-scenes-recovery-assistance-640.webp 640w, /optimized/care-scenes-recovery-assistance-1440.webp 1440w"
  },
  "/brand/andora-private-duty-home-health.png": {
    "width": 800,
    "height": 577,
    "src": "/optimized/brand-andora-private-duty-home-health-800.webp",
    "srcSet": "/optimized/brand-andora-private-duty-home-health-640.webp 640w, /optimized/brand-andora-private-duty-home-health-800.webp 800w"
  }
};
