import { MapPin } from 'lucide-react';
import Section from '../components/Section';
import SEO from '../components/SEO';

const areas = ['Downtown Houston', 'Memorial', 'Texas Medical Center', 'Heights', 'River Oaks', 'West University', 'Bellaire', 'Energy Corridor', 'Katy', 'Sugar Land', 'Pearland', 'Cypress', 'Spring', 'The Woodlands'];

export default function ServiceAreasPage() {
  return <><SEO title="Houston Home Care Service Areas | Andora Home Care" description="Andora provides private-duty nursing, personal care, respite care, and around-the-clock support across Houston, Memorial, Downtown, and nearby communities." canonical="/service-areas" /><Section className="bg-gradient-to-br from-blue-50 to-white pt-24 pb-12"><div className="mx-auto max-w-3xl text-center"><MapPin className="mx-auto mb-4 text-primary" size={38} /><h1 className="heading-1 mb-6">Home Care Across Houston and Nearby Communities</h1><p className="text-lg leading-relaxed text-gray-600">Andora helps families coordinate private-duty nursing, personal care, respite care, and ongoing support throughout Greater Houston. Availability depends on the care needs, schedule, and licensed service area, so our team confirms details before services begin.</p></div></Section><Section><div className="mx-auto grid max-w-4xl gap-10 md:grid-cols-2"><div><h2 className="heading-2 mb-4">Communities we commonly serve</h2><ul className="grid grid-cols-2 gap-3 text-gray-700">{areas.map((area) => <li key={area} className="rounded-lg bg-gray-50 px-4 py-3">{area}</li>)}</ul></div><div className="rounded-2xl bg-primary p-8 text-white"><h2 className="text-3xl font-bold mb-4">Not sure if you’re in range?</h2><p className="mb-6 leading-7 text-blue-100">Call us to discuss the kind of support you need, your schedule, and your location. We’ll confirm current availability before making any commitment.</p><a href="tel:+18326793716" className="inline-flex rounded-lg bg-white px-5 py-3 font-semibold text-primary">Call (832) 679-3716</a></div></div></Section></>;
}
