import { readFile, writeFile, readdir, mkdir, stat } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { join } from 'node:path';

const { default: sharp } = await import(process.env.ANDORA_SHARP_PATH || 'sharp');
const root = fileURLToPath(new URL('../', import.meta.url));
const output = join(root, 'public/optimized');
await mkdir(output, { recursive: true });
const sources = [];
async function collect(dir) {
  for (const entry of await readdir(dir, { withFileTypes: true })) {
    const path = join(dir, entry.name);
    if (entry.isDirectory()) await collect(path);
    else if (/\.tsx$/.test(path)) sources.push(await readFile(path, 'utf8'));
  }
}
await collect(join(root, 'src'));
const files = new Set([...sources.join('\n').matchAll(/["'](\/[^"'\n]+\.(?:png|jpe?g))["']/gi)].map(match => match[1]));
// Shared brand configuration supplies this path dynamically to header/footer.
files.add('/brand/andora-private-duty-home-health.png');
const manifest = {};
let before = 0;
let after = 0;
for (const source of files) {
  const input = join(root, 'public', source.slice(1));
  const metadata = await sharp(input).metadata();
  const name = source.slice(1).replace(/\.[^.]+$/, '').replace(/[^a-z0-9]+/gi, '-').toLowerCase();
  const variants = [];
  for (const target of [640, 1440]) {
    const width = Math.min(target, metadata.width);
    if (variants.some(variant => variant.width === width)) continue;
    const filename = `${name}-${width}.webp`;
    const result = await sharp(input).rotate().resize({ width, withoutEnlargement: true }).webp({ quality: 82 }).toFile(join(output, filename));
    variants.push({ src: `/optimized/${filename}`, width: result.width });
    after += result.size;
  }
  before += (await stat(input)).size;
  manifest[source] = { width: metadata.width, height: metadata.height, src: variants.at(-1).src, srcSet: variants.map(v => `${v.src} ${v.width}w`).join(', ') };
}
await writeFile(join(root, 'src/lib/imageManifest.ts'), '// Generated by scripts/optimize-images.mjs. Originals are preserved.\nexport default ' + JSON.stringify(manifest, null, 2) + ';\n');
console.log(JSON.stringify({ images: files.size, originalBytes: before, optimizedBytesAllVariants: after }));
